name = "aoc2025"
uuid = "db2870c7-8254-4705-ad21-dab72070d109"
version = "0.1.0"
authors = ["David Hanak <dhanak@gmail.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
UnionFind = "99c6138d-4661-531e-8606-19bf1ec96588"

[compat]
Combinatorics = "1.0.3"
HiGHS = "1.20.1"
JuMP = "1.29.3"
MacroTools = "0.5.16"
UnionFind = "0.1.0"
