name = "aoc2025"
uuid = "db2870c7-8254-4705-ad21-dab72070d109"
authors = ["David Hanak <dhanak@gmail.com>"]
version = "0.1.0"

[deps]
# Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
# DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
# Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
# Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
# Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
